# Generated by Django 2.2.5 on 2019-12-30 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20190526_0152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-created_at'], 'verbose_name_plural': '컨텐츠'},
        ),
    ]
